name: Test

on:
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+-rc'

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
        - admin
        - api

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: node-12-${{ matrix.project }}

    - name: Install dependencies
      run: npm ci
      working-directory: ./${{ matrix.project }}

    - name: Build
      env: 
        REACT_APP_SHOPIFY_API_KEY: ${{ secrets.TEST_SHOPIFY_API_KEY }}
      run: npm run build --if-present
      working-directory: ./${{ matrix.project }}

    - name: Test
      run: npm run test --if-present
      working-directory: ./${{ matrix.project }}

    - name: Run build script
      run: ./.github/scripts/build.sh ${{ matrix.project }}
      shell: bash


    # - name: Setup deploy variables
    #   env:
    #     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    #   run: |
    #     echo ::set-env name=IMAGE_TAG::${{ secrets.DOCKER_REGISTRY }}/shopify/${{ matrix.project }}:${GITHUB_REF#refs/tags/}
    #     echo ::set-env name=AZURE_PUBLISH_PROFILE_SECRET_NAME::$( echo "TEST_AZURE_WEBAPP_PUBLISH_PROFILE_${{ matrix.project }}" | tr [:lower:] [:upper:] )

    # - name: Docker build
    #   run: docker build . -t $IMAGE_TAG
    #   working-directory: ./${{ matrix.project }}
    
    # - name: Docker login
    #   uses: azure/docker-login@v1
    #   with:
    #     login-server: ${{ secrets.DOCKER_REGISTRY }}
    #     username: ${{ secrets.DOCKER_REGISTRY_USER }}
    #     password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    
    # - name: Docker push
    #   run: docker push $IMAGE_TAG
    #   working-directory: ./${{ matrix.project }}